<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="20390" started-at="2022-11-13T06:26:17Z" finished-at="2022-11-13T06:26:38Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="20390" started-at="2022-11-13T06:26:17Z" finished-at="2022-11-13T06:26:38Z">
      <class name="webdriver_api.Topic_8_Window_Tab_Exercise">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:webdriver_api.Topic_8_Window_Tab_Exercise@174d20a]" name="beforeTest" is-config="true" duration-ms="1865" started-at="2022-11-13T13:26:17Z" finished-at="2022-11-13T13:26:19Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="FAIL" signature="TC_04_Windows_Tab()[pri:0, instance:webdriver_api.Topic_8_Window_Tab_Exercise@174d20a]" name="TC_04_Windows_Tab" duration-ms="18514" started-at="2022-11-13T13:26:19Z" finished-at="2022-11-13T13:26:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [automationfc.com@gmail.com] but found [Automation FC]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [automationfc.com@gmail.com] but found [Automation FC]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at webdriver_api.Topic_8_Window_Tab_Exercise.TC_04_Windows_Tab(Topic_8_Window_Tab_Exercise.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TC_04_Windows_Tab -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:webdriver_api.Topic_8_Window_Tab_Exercise@174d20a]" name="afterTest" is-config="true" duration-ms="0" started-at="2022-11-13T13:26:38Z" finished-at="2022-11-13T13:26:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- webdriver_api.Topic_8_Window_Tab_Exercise -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
